<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>手写Promise_09_catch方法</title>
        <script src="./index.js"></script>
    </head>
    <body>
        <!-- 
            1、catch方法也是有返回值的，返回的也是新的Promise实例化对象
            2、catch方法返回值也和then的返回值类似
                2.1、返回的是一个非Promise实例化对象，则得到的是一个成功的Promise对象，返回值就是结果值
                2.2、返回的是一个Promise实例化对象，则得到的结果和返回的结果相同
                2.3、如果有异常信息，则得到的是一个失败的Promise实例化对象，结果为异常信息。
         -->
        <script>
            const pms1 = new Promise((resolve, reject) => {
                setTimeout(() => {
                    // resolve(100);
                    reject("error");
                    // throw "异常";
                }, 1000);
            });

            const pms2 = pms1.catch((reason) => {
                // console.log(reason);
                // return reason;
                // return new Promise((resolve, reject) => {
                //     // resolve(200);
                //     reject("error");
                // });
                throw "异常";
            });

            console.log(pms2);
        </script>
    </body>
</html>
